#================================================================================================#
#                                                                                                #
# ███╗   ███╗██╗   ██╗     █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗ #
# ████╗ ████║╚██╗ ██╔╝    ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝ #
# ██╔████╔██║ ╚████╔╝     ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝  #
# ██║╚██╔╝██║  ╚██╔╝      ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝   #
# ██║ ╚═╝ ██║   ██║       ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║    #
# ╚═╝     ╚═╝   ╚═╝       ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝    #
#                                                                                                #
#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗                                                 #
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝                                                 #
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗                                                #
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║                                                #
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝                                                #
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝                                                 #
#                                                                                                #
#================================================================================================#

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c8f8f"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#21c7a8"
magenta = "#ae81ff"
red = "#ff5874"
white = "#d6deeb"
yellow = "#ecc48d"

[colors.cursor]
cursor = "#9ca1aa"
text = "#080808"

[colors.normal]
black = "#1d3b53"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#a1cd5e"
magenta = "#c792ea"
red = "#fc514e"
white = "#a1aab8"
yellow = "#e3d18a"

[colors.primary]
background = "#011627"
bright_foreground = "#eeeeee"
foreground = "#acb4c2"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Sauce Code Pro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Sauce Code Pro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Sauce Code Pro Nerd Font"
style = "Italic"

[font.normal]
family = "Sauce Code Pro Nerd Font"
style = "Regular"

[window]
#gtk_theme_variant = "Dark"
opacity = 0.75
